my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: [robling_partner.east-us-2.azure]

      # User/password auth
      user: [hrai]
      password: [LisNepal#20]

      role: [READ_NONPRD]
      database: [TEST_DB]
      warehouse: [DEMO_WH]
      schema: [DBT]
      threads: [1 or more]
      client_session_keep_alive: False
      query_tag: [anything]

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false
      reuse_connections: False # default: false (available v1.4+)